agnostic_nms: true
amp: true
augment: false
auto_augment: randaugment
batch: -1
bgr: 0.0
box: 7.5
cache: false
cfg: null
classes: null
close_mosaic: 20
cls: 0.1
conf: null
copy_paste: 0
copy_paste_mode: flip
cos_lr: false
crop_fraction: 1.0
data: dataset.yaml
degrees: 10
deterministic: true
device: 0
dfl: 0.3
dnn: false
dropout: 0.0
dynamic: false
embed: null
epochs: 100
erasing: 0
exist_ok: false
fliplr: 0.5
flipud: 0.5
format: torchscript
fraction: 1.0
freeze: None
half: false
hsv_h: 0.0
hsv_s: 0.1
hsv_v: 0.1
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: 1
lr0: 0.001
lrf: 0.01
mask_ratio: 4
max_det: 10
mixup: 0
mode: train
model: yolo11s.pt
momentum: 0.937
mosaic: 1
multi_scale: false
name: bombusaddfps_11s_001_640_FRESH
nbs: 64
nms: false
opset: null
optimize: false
optimizer: SGD
overlap_mask: true
patience: 20
perspective: 0.0
plots: true
pose: 12.0
pretrained: true
profile: false
project: bee_cam_sahi_test
rect: false
resume: false
retina_masks: false
save: true
save_conf: true
save_crop: false
save_frames: false
save_hybrid: false
save_json: true
save_period: -1
save_txt: true
scale: 0.1
seed: 0
shear: 0.0
show: false
show_boxes: true
show_conf: true
show_labels: false
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.1
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
workspace: 0
